---
title: Research and Work Experience
---

1. Research Intern, TCS Research [Mentor: Supriya Agrawal]
    * Generated automated test cases using decision trees and random forests for bug-testing and detection  in real software systems. I used
      different encoding mechanisms for categorical variables and applied boundary coverage and crossover techniques to increase testcases 
      coverage. 
    * Employed classical tree-search algorithms on popular libraries like Sklearn, CatBoost, H2o, XGBoost and LightGBM. This helped build fuzzy 
      logic involving time and sequence of operations. For example: The wiper of a car has several tasks which executed in a proper sequence give 
      signal for the wipers to turn on. 

2. Research Intern, IIT Gandhinagar [Mentor: Prof. Nipun Batra]
    * Contributed to "pyprobml" owned by Prof.Kevin Murphy, Google Research for figures in his book, "Machine Learning: A Probabilistic 
      Perspective."
    * Modified the SOTA Seq2Point to predict mean and sigma appliance power consumption on the publicly available energy dataset REDD dataset. 
      Quantified uncertainty through approximate Bayesian methods like Deep Ensemble, Bootstrap and MC Dropout in NILM-Uncertainty.

3. Functional Analyst Intern, HDFC Bank [Mentor: Pravesh Suvarna]
    * Researched startups offering products and services leveraging machine learning or blockchain to assist in scaling services during peak 
      traffic moments. For example: Analysis of 30-40 concurrent million users on Disney-Hotstar during ODI World Cup is performed to identify 
      future failure points in advance. 
    * Performed unit tests for netbanking interface. Prepared business requirement documents comprising of technical stack with business logic. 
      For example: A transaction email classifier to automate email classification which is done manually at the moment. Used bag of words, mneumonic 
      master to classify transactions to appropriate tiers. 

4. Deep Learning Intern, Mastek [Mentor: Anjali Sohoni Bhide]
    * Explored Intel OpenVINO, an open source deep learning inference engine for real time use in use cases like Amazon Go. Ran deep learning models
      for downstream classification tasks like object detection, instance segmentation and many more and collected insights, deductions and time 
      analysis pertaining to different layers of a neural network. 
    * Studied applications of OpenVINO in real world usecases like injury prevention, survelliance in high profile sports games like FIFA World cup 
      2018, medical surgery and much more. 

5. App Developer Intern, Pravaig Dynamics [Mentor: Siddhartha Bagri]
    * Implemented a robo-taxi app with user and driver side pages with login, sign-up, ride scheduling and communication features. Used open source
      libraries like React-Native and Supabase for all components from backend to the frontend. Proceeded by an iterative process of database
      schema design, feedback, ideation, development and improvement.


